# Generated by Django 6.0.2 on 2026-02-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_adv_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='adv',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Изображение объявления'),
        ),
        migrations.AddField(
            model_name='adv',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка (при клике)'),
        ),
        migrations.AddField(
            model_name='adv',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='adv',
            name='position',
            field=models.CharField(choices=[('sidebar', 'Sidebar'), ('infeed', 'In-feed'), ('header', 'Header')], default='sidebar', max_length=32, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='adv',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL сілтемесі'),
        ),
    ]
